---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hypr-nvidia
# description will be included in the image's metadata
description: messing around

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sway-atomic-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/errornointernet/packages/repo/fedora-%OS_VERSION%/errornointernet-packages-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
      - https://repo.librewolf.net/librewolf.repo
      #- https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser.repo
    install:
      - micro
      - starship
      - ghostty

      # power
      - tuned-ppd
      
      # WM
      - niri
      - xwayland-satellite
      #- gnome-themes-extra
      #- gnome-icon-theme
      #- paper-icon-theme
      #- breeze-icon-theme 
      - papirus-icon-theme
      - xdg-desktop-portal-gnome # needed for niri screencasting
      - gnome-keyring
      - hyprland
      #- hyprlang
      - hyprlock
      - hyprutils
      - hypridle
      #- swayidle
      #- swaylock
      #- swaybg
      - yazi
      - nwg-look
      - nu
      - waypaper
      - librewolf
      #- zen-browser

      # display
      - wlr-randr
      - wlsunset
      #- light
      #- kanshi
      
      # screenshot
      - slurp
      - grim

      # networking
      - NetworkManager-tui
      - tailscale
      
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: fonts
    fonts:
      nerd-fonts:
        - Iosevka
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - google-noto-emoji-fonts

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
     # remove:

  #- type: systemd
  #  system:
  #    enabled:
  #      - tune-ppd.service  # this enables tune-ppd
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

